# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentree < Formula
  desc "Create and manage isolated Git worktrees for AI coding agents"
  homepage "https://github.com/AryaLabsHQ/agentree"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.1.0/agentree_Darwin_x86_64.tar.gz"
      sha256 "e2aaf1d5bfc2d6ce033c29c7fcbaeeac9896c8d70870917be382d68a713f7ec5"

      def install
        bin.install "agentree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.1.0/agentree_Darwin_arm64.tar.gz"
      sha256 "b4c92248590b2805cbfc541269083a148a890fd660f5b2650dc3f8869ee35529"

      def install
        bin.install "agentree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.1.0/agentree_Linux_x86_64.tar.gz"
      sha256 "83e9dc360603159ed508ce29cb7ad330f7e6ef5bb6de463d04bf444c0bc78556"
      def install
        bin.install "agentree"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.1.0/agentree_Linux_arm64.tar.gz"
      sha256 "7574c585e1967d325e4cf637fc0f5c472b7c1936877c5508fe9f271d57eb65fc"
      def install
        bin.install "agentree"
      end
    end
  end

  test do
    system "#{bin}/agentree", "--version"
  end
end
