# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentree < Formula
  desc "Create and manage isolated Git worktrees for AI coding agents"
  homepage "https://github.com/AryaLabsHQ/agentree"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.0.0/agentree_Darwin_x86_64.tar.gz"
      sha256 "931176b1770ab13118506a57e6bdf099e258cdffec7d422342751bfa4b616264"

      def install
        bin.install "agentree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.0.0/agentree_Darwin_arm64.tar.gz"
      sha256 "fa5680f9be2d38b959423663090a6b36338997150fe447ffe9068ef723748125"

      def install
        bin.install "agentree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.0.0/agentree_Linux_x86_64.tar.gz"
      sha256 "ec842436d670ed62b6ccd0d712b32a90d4f52120a7b48bf3284e1848ca52368e"
      def install
        bin.install "agentree"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AryaLabsHQ/agentree/releases/download/v1.0.0/agentree_Linux_arm64.tar.gz"
      sha256 "d7659fe76bb856667e8d3fa3604d10b4bbb061d810e531ea4af090d87d18ab33"
      def install
        bin.install "agentree"
      end
    end
  end

  test do
    system "#{bin}/agentree", "--version"
  end
end
