# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hatch < Formula
  desc "Create and manage isolated Git worktrees for agentic workflows"
  homepage "https://github.com/AryaLabsHQ/hatch"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AryaLabsHQ/hatch/releases/download/v1.0.0/hatch_Darwin_x86_64.tar.gz"
      sha256 "138ced9f87037acc38d5729d3e3a6154e0f423fd1201f9ac66731250ab9949d3"

      def install
        bin.install "hatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AryaLabsHQ/hatch/releases/download/v1.0.0/hatch_Darwin_arm64.tar.gz"
      sha256 "ee116914f5132273957b8214d5d5eab7c4ade81f8e1671f4007574251fba0fa5"

      def install
        bin.install "hatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AryaLabsHQ/hatch/releases/download/v1.0.0/hatch_Linux_x86_64.tar.gz"
      sha256 "0f0a2d13149c39b2adfdcfc4abb848945eac1e4db61baa1fcad383bcc7fc0a2f"
      def install
        bin.install "hatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AryaLabsHQ/hatch/releases/download/v1.0.0/hatch_Linux_arm64.tar.gz"
      sha256 "81da24edb15566305c08d97f07d19c4e96b5be006e555813e24a26fd9e4e986f"
      def install
        bin.install "hatch"
      end
    end
  end

  test do
    system "#{bin}/hatch", "--version"
  end
end
